### PR TITLE
Merge Master from Staging

### PR DESCRIPTION
**Pull request by Khalil9022**

### CODE REVIEW

**Review by TheaKevin — APPROVED** [review]
Dear Khalil, your code looks good to me, you can merge it to master. Thank you for your hard work

**Review by fikriaplubis — APPROVED** [review]
Dear khalil, your works looks good to me, we can merge it to master, thank you.

**Review by WibuSOS — APPROVED** [review]
This build has been accepted by our user. Therefore, it's deployable to Master now. Good luck!

**Review by julyusmanurung — APPROVED** [review]
Hi @Khalil9022 

After viewed 77 files changed and tested in my local, I see no problem here. That's all working properly. What a speed run for the second sprint. Now you can merge it. Thanks for your hard work. LGTM 👍.

best regards;
Julyus Andreas

**Pull request merged**
