### PR TITLE
Deployment to Master

### PR DESCRIPTION
**Pull request by WibuSOS**

### CODE REVIEW

**Review by TheaKevin — APPROVED** [review]
Dear Vincent Joyan, LGTM,  you can merged it to master. Thanks for your hard work.

**Review by julyusmanurung — APPROVED** [review]
Hi Everyone

LGTM 👍, It's a good milestone for us in this sprint 1 stage. Maybe we have to refactoring some codes to make our code clean and easy to understand.

best regards;
Julyus

**Review by fikriaplubis — APPROVED** [review]
looks good to me

**Review by Khalil9022 — APPROVED** [review]
LGTM, application work smoothly and no error for sure

**Pull request merged**
