### PR TITLE
[REFACTOR] fix delete database in STAGING if exist

### PR DESCRIPTION
**Pull request by Khalil9022**

### CODE REVIEW

**Review by TheaKevin — APPROVED** [review]
Dear Khalil, your code looks good to me, you can merge it to staging. Thank you for your hard work

**Review by julyusmanurung — APPROVED** [review]
Hi Khalil,

Nice job! it's working properly on my localhost. Now you can merged it. Thanks for your hard work.

best regards;
Julyus Andreas

**Review by WibuSOS — APPROVED** [review]
Looks good to me, there should be no problem with this fix. Hopefully, the tables will be successfully dropped after this patch deployed. Good luck!

**Review by fikriaplubis — APPROVED** [review]
looks good to me, thank you

**Pull request merged**
