### PR TITLE
Pbi 26 localization

### PR DESCRIPTION
**Pull request by julyusmanurung**
- localization for static page is working properly

### CODE REVIEW

**Review by Khalil9022 — APPROVED** [review]
Looking good, When try to run this app , it works smoothly.. thanks Jul

**Comment by julyusmanurung** [comment]
finally guys..... setelah 9 kali percobaan commit

**Review by TheaKevin — APPROVED** [review]
Dear Julyus, your code looks good to me, you can merge it to staging. Thank you for your hard work

**Review by fikriaplubis — APPROVED** [review]
Dear Julyus, your works looks good to me, thank you for your hard work.

**Review by WibuSOS — APPROVED** [review]
Looks good to me, it's deployable now. Good luck!

**Pull request merged**
