### PR TITLE
Merge Branch Master From Staging

### PR DESCRIPTION
**Pull request by Khalil9022**
- add localization
- fix language.json 
- add user profile, update profile
- UI Improvement

### CODE REVIEW

**Review by TheaKevin — APPROVED** [review]
Dear Khalil, your code looks good to me, you can merge it to master. Thank you for your hard work.

**Review by julyusmanurung — APPROVED** [review]
Hi Khalil

It's working properly, now you can merge it. Thank you for your hard work.

Best regards;
Julyus Andreas

**Review by fikriaplubis — APPROVED** [review]
Thank you everyone, this is the end of sprint 3. Lets merged it to master.

**Review by WibuSOS — APPROVED** [review]
Looks good to me! You can merge this to master. Thanks all for your hard work!

**Pull request merged**
