### PR TITLE
Pbi 26 localization

### PR DESCRIPTION
**Pull request by TheaKevin**
+ All Localization in frontend done
+ Change front end design for user to easily use SiMiddleman+

### CODE REVIEW

**Review by Khalil9022 — APPROVED** [review]
Hallo Thea, this code looks good to me, and then when running the  program doesnt seem error.. Good

**Review by julyusmanurung — APPROVED** [review]
Hi Thea,

Thanks for solving bugs in vercel deployment. I already test it in my local and everything working properly. Now you can merge it, thank you for your hard work.

best regards;
Julyus Andreas

**Review by WibuSOS — APPROVED** [review]
Looks good to me, it's deployable now!

**Review by fikriaplubis — APPROVED** [review]
Dear Thea, your works looks good to me, thank you

**Pull request merged**
