### PR TITLE
Staging

### PR DESCRIPTION
**Pull request by fikriaplubis**
- PBI 16 Done
- Integrate with SonarCloud Code Review

### CODE REVIEW

**Review by TheaKevin — APPROVED** [review]
Dear Fikri, your works looks good to me, you can merged it to master. Thanks for your hard work.

**Review by julyusmanurung — APPROVED** [review]
Hi Fikri,

Good job, it's working properly 👍

best regards;
Julyus Andreas

**Review by WibuSOS — APPROVED** [review]
Good job to everyone involved! You can deliver this to production as soon as you can.

**Review by Khalil9022 — APPROVED** [review]
Looks good, the application work smoothly, great job fikri

**Comment by fikriaplubis** [comment]
Thank you all, great job for today, comeback stronger tomorrow!

**Pull request merged**
