### PR TITLE
Pbi 23 view profile

### PR DESCRIPTION
**Pull request by WibuSOS**
Final README.md

### CODE REVIEW

**Review by TheaKevin — APPROVED** [review]
Dear Vincent, your code looks good to me, you can merge it to staging. Thank you for your hard work.

**Review by julyusmanurung — APPROVED** [review]
Hi Fikri

Nice works. Now you can merge it.

Thank you

**Review by fikriaplubis — APPROVED** [review]
The explanation looks good, thank you.

**Review by Khalil9022 — APPROVED** [review]
Hello Joyan, when im checking the application it works normally and no error, thanks for your hardwork to edit the Readme ^^

**Pull request merged**
