### PR TITLE
julyus-pbi-6-create-rooms: re-pull request for add room details

### PR DESCRIPTION
**Pull request by julyusmanurung**
Repull request because there is a change in codiga for "function too long"

### CODE REVIEW

**Review by Khalil9022 — APPROVED** [review]
Dear Julyus, Looks Good to me, no error in running

**Review by TheaKevin — APPROVED** [review]
Dear Julyus, your works looks good to me, you can merged it to staging. Thanks for your hard work.

**Review by WibuSOS — APPROVED** [review]
Still within acceptable criteria, good to merge. Good luck!

**Review by fikriaplubis — APPROVED** [review]
Dear Julyus, your works looks good to me, you can merge it to staging, thank you.

**Pull request merged**
