### PR TITLE
Pbi 23 view profile

### PR DESCRIPTION
**Pull request by TheaKevin**
- view profile done
- update profile done
- test coverage 100%

### CODE REVIEW

**Review by Khalil9022 — APPROVED** [review]
Woaahhh, thanks Thea for the hard work.. the application looks good and no error acquire :D

**Review by fikriaplubis — APPROVED** [review]
Dear Thea, your works looks good to me, you can merged it to staging, thank you.

**Review by WibuSOS — APPROVED** [review]
Looks good and cool! We are done bois!

**Review by julyusmanurung — APPROVED** [review]
Hi @TheaKevin 

Finally... everything is fine. Looks good to me. Thank you for your hard work. Now you can merge it. 

best regards;
Julyus Andreas

**Pull request merged**
