### PR TITLE
great pull request for deployment

### PR DESCRIPTION
**Pull request by julyusmanurung**

### CODE REVIEW

**Review by WibuSOS — APPROVED** [review]
Sangat ok, deliverable ya

**Review by TheaKevin — APPROVED** [review]
Dear Julyus, your works looks good to me, you can merged it to master. Thanks for your hard work.

**Comment by julyusmanurung** [comment]
SonarCloud Quality Gate failed because
- Failed condition 0.0% 0.0% Coverage on New Code (is less than 80%) => because it's not implemented yet
- Failed condition 20.2% 20.2% Duplicated Lines (%) on New Code (is greater than 3%) => duplicate lines (occurred only in `x_testing.go`)

**Comment by Khalil9022** [comment]
Bisa dirunning dan tidak ada kendala

**Review by Khalil9022 — APPROVED** [review]
Code berjalan dengan baik

**Review by fikriaplubis — APPROVED** [review]
Dear Julius, the code review by SonarCloud still seems to be a flop, but i think thats not really important, you can continue merge it to master. thank you.

**Pull request merged**
