### PR TITLE
PBI 12 - Open Room Chat - Merge staging to master 

### PR DESCRIPTION
**Pull request by Khalil9022**
Merging from branch staging to master

### CODE REVIEW

**Review by TheaKevin — APPROVED** [review]
Dear Khalil, LGTM, you can merged it to master. Thanks for your hard work.

**Review by julyusmanurung — APPROVED** [review]
Hi Khalil,

LGTM 👌

best regards;
Julyus Andreas

**Review by fikriaplubis — APPROVED** [review]
Dear Khalil, your worked looks good to me, you can merge it to master, thank you.

**Review by WibuSOS — APPROVED** [review]
Looks good to me, safe to merge this to master

**Pull request merged**
